### ISSUE TITLE
Please filter email addresses

### ISSUE THREAD

**Issue by analog-nico** [npmdoc/node-npmdoc-hpp#1]
Could you please filter the email addresses that appear in the verbatim copy of the package.json?

Having email addresses visible as plain text on the web is just asking for even more spam...

Thanks!

**Comment by kaizhu256** [comment]
hi Nicolai, removed the email and added you as a contributor to npmdoc-hpp package.  plan to implement a patch later to partially mask all emails and apply it retroactively to rest of npmdoc’s.

sorry for the inconvenience ^^;;;
-kai

On Apr 12, 2017 8:43 AM, "Nicolai Kamenzky" <notifications@github.com> wrote:
Could you please filter the email addresses that appear in the verbatim copy of the package.json?

Having email addresses visible as plain text on the web is just asking for even more spam...

Thanks!

**Comment by analog-nico** [comment]
Thanks, buddy! I can still see my email in the README on GitHub, though.

What is the purpose of your package family, btw?

**Comment by kaizhu256** [comment]
> Thanks, buddy! I can still see my email in the README on GitHub, though.
> 
oops.  thx, removed email from github readme ^^;;;
> What is the purpose of your package family, btw?
> 

public-service to document and provide basic test-coverage (via sister npmtest- family) for the top 1% of npm-packages (by stars), which would be ~5000 packages.

i’m currently fixing edge-cases for certain packages that fail the doc-generator and test-coverage generator.  most of the failing packages are shell-based cli tools (that install themselves in .bin folder), and don’t have an actual ‘npm’ module to require.

**Comment by kaizhu256** [comment]
merged PR https://github.com/kaizhu256/node-utility2/pull/6/files#diff-2bd0551199a05c1f904d28f33a4dbf69R611

confirmed emails are stripped from sites:
https://www.npmjs.com/package/npmdoc-hpp
https://github.com/npmdoc/node-npmdoc-hpp

**Comment by analog-nico** [comment]
Thank you. Keep up the great work!
